
services:
  frontend:
    build: ./
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./.env

  db:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres_db
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - elasticsearch

    
volumes:
  pgdata:
  esdata:
